---
version: "3.7"
services:
  metube-tailscale:
    env_file: .env
    image: pknw1/metube-tailscale 
    hostname: metube-tailscale
    container_name: metube-tailscale
    environment:
      - HTTP_PROXY=http://squid-tailscale:3128
      - TS_AUTHKEY=${TAILSCALE_AUTH}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_ENABLE_METRICS=true
    volumes:
      - ./config/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    networks:
      - tailscale_proxy
    dns:
      - 8.8.8.8
    restart: unless-stopped
    ports:
      - 8180:8081

networks:
  tailscale_proxy:
    external: true
